server:
  port: 8762
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://127.0.0.1:8001/eureka/
#  instance:
#    hostname: server1
#spring:
#  application:
#    name: eurka-server1