server:
  port: 8761
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#server.port: 指明了应用启动的端口号
#eureka.instance.hostname: 应用的主机名称
#eureka.client.registerWithEureka: 值为false意味着自身仅作为服务器，不作为客户端
#eureka.client.fetchRegistry: 值为false意味着无需注册自身
#eureka.client.serviceUrl.defaultZone: 指明了应用的URL
spring:
  application:
    name: eurka-server